### ISSUE TITLE
你好，请问你有没有mxshop-api对应yapi文件

### ISSUE THREAD

**Issue by bubbleboy11** [CPALyth/mxshop_api#1]

**Comment by stdeson** [comment]
有的, 你要哪种格式的?

**Comment by bubbleboy11** [comment]
导入yapi测试接口的

**Comment by stdeson** [comment]
「api.json」，点击链接保存，或者复制本段内容，打开「阿里云盘」APP ，无需下载，极速在线查看享用。
链接：https://www.aliyundrive.com/s/Gac23bnJqrj

**Comment by bubbleboy11** [comment]
谢谢老哥啦

**Comment by stdeson** [comment]
嘿嘿, 小事

**Comment by guaosi** [comment]
@bubbleboy11 @CPALyth 文件过期了，可以重新分享一下吗

**Comment by stdeson** [comment]
![image](https://user-images.githubusercontent.com/51091135/159446207-74f27fc9-09d5-4cae-908c-3b96c875cd21.png)
sorry, 我这也没有了

**Comment by cz321** [comment]
> 谢谢老哥啦

老哥，这个测试文件还在吗，我也需要
